// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    CollapseTransition: typeof import('./../components/ui/collapseTransition/Index.vue')['default']
    ConfigProvider: typeof import('./../components/business/configProvider/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
